### ISSUE TITLE
Issue with test_os_its003.c

### ISSUE THREAD

**Issue by tvidyasagar** [ARM-software/bsa-acs#80] opened 2022-12-19 07:10 UTC
Hi,
Looking at the code in test_os_its003.c, it seems to assume that there is only one SMMU in the system. If we have a system like the one attached in the pic where we have multiple SMMU instances and PCIe RCs behind them having same StreamIDs, then, uniqueness of streamID should always be checked in the context of the specific SMMU instance i.e. to put it differently, in the context of a specific output reference.
![BSA_StreamID_Uniqueness_Test_Issue](https://user-images.githubusercontent.com/62286018/208368000-d3ad5d90-aabb-4a05-88ca-4cf3722f379b.jpg)

**Comment by rajatgoyal47** [comment] 2023-01-11 07:36
Hi Vidya,

Thank you for reporting this.
We will fix this and upstream the changes soon. 

Thanks,
Rajat Goyal
ACS Team

**Comment by rajatgoyal47** [comment] 2023-01-12 05:12
Hi Vidya,

Fix has been merged as part of #81
Thanks for reporting this.

Rajat Goyal
ACS Team

**Comment by chetan-rathore** [comment] 2023-01-23 11:02
Hi @tvidyasagar, 

Closing the issue now. Please reopen if the issue is seen.

Thanks,
ACS team

**Closed by chetan-rathore** 2023-01-23 11:02 UTC
