### ISSUE TITLE
missing \n in info block

### ISSUE THREAD

**Issue by hrw** [ARM-software/bsa-acs#92] opened 2023-01-25 10:05 UTC
During tests of qemu/sbsa-ref I got this weird output:

``` 
 GIC_INFO: Number of ITS              :    0

 GTDT don't have el2 virt timer info
 using bsa recommended value 28 TIMER_INFO: Number of system timers  :    0
 WATCHDOG_INFO: Number of Watchdogs   :    1
```

Looks like forgotten "\n" in some message.

**Comment by chetan-rathore** [comment] 2023-01-27 15:16
Hi @hrw, 

This seems to be a duplicate of #94.
If that's the case, can you please close this issue. 
The required changes will be made with #94 fix PR.

Thanks,
ACS team

**Closed** 2023-01-27 15:28 UTC
