### ISSUE TITLE
Test 205 (Non-secure SGIs are implemented) shouldn't check invalid PE cores

### ISSUE THREAD

**Issue by sunnywang-arm** [ARM-software/bsa-acs#102] opened 2023-01-30 16:25 UTC
Test currently not checking the correct base address of GIC RD of a PE.

**Comment by chetan-rathore** [comment] 2023-02-20 05:07
Hi @sunnywang-arm,

Bug fix for the issue is raised https://github.com/ARM-software/bsa-acs/pull/109. The changes are under verification and PR will be merged once verified.

Thanks,
ACS team

**Comment by sunnywang-arm** [comment] 2023-02-20 10:12
Verified the fix. It worked fine, so closed the issue.

**Comment by sunnywang-arm** [comment] 2023-02-20 10:13
Reopen it to wait for merging.

**Comment by chetan-rathore** [comment] 2023-02-20 15:30
Hi @sunnywang-arm, 

Thanks for helping in the verification of the fix, the changes are merged.

**Closed** 2023-02-20 15:50 UTC
